from lib.database.tables.CustomCommand import CustomCommand
from lib.database.tables.Feedback import Feedback
from lib.database.tables.HiddenChannel import HiddenChannel
from lib.database.tables.Keyword import Keyword
from lib.database.tables.Level import Level
from lib.database.tables.LevelIgnoreChannel import LevelIgnoreChannel
from lib.database.tables.LevelRole import LevelRole
from lib.database.tables.Reminder import Reminder
from lib.database.tables.Server import Server
from lib.database.tables.Statistic import Statistic
from lib.database.tables.Telemetry import Telemetry
from lib.database.tables.User import User