from lib.dbModules.tableInterfaces.CustomCommandDB import CustomCommandDB
from lib.dbModules.tableInterfaces.FeedbackDB import FeedbackDB
from lib.dbModules.tableInterfaces.HiddenChannelDB import HiddenChannelDB
from lib.dbModules.tableInterfaces.KeywordDB import KeywordDB
from lib.dbModules.tableInterfaces.LevelDB import LevelDB
from lib.dbModules.tableInterfaces.LevelIgnoreChannelDB import LevelIgnoreChannelDB
from lib.dbModules.tableInterfaces.LevelRoleDB import LevelRoleDB
from lib.dbModules.tableInterfaces.ReminderDB import ReminderDB
from lib.dbModules.tableInterfaces.ServerDB import ServerDB
from lib.dbModules.tableInterfaces.StatisticDB import StatisticDB
from lib.dbModules.tableInterfaces.TelemetryDB import TelemetryDB
from lib.dbModules.tableInterfaces.UserDB import UserDB